<?php

namespace Database\Seeders\Customizes;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Customizes\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 参考：https://ja.wikipedia.org/wiki/ISO_3166-1
        Country::create(['country_code'=>'IS','country_name_j'=>'アイスランド','country_name_e'=>'Iceland','country_code_a3'=>'ISL','country_code_n3'=>'352','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IE','country_name_j'=>'アイルランド','country_name_e'=>'Ireland','country_code_a3'=>'IRL','country_code_n3'=>'372','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AZ','country_name_j'=>'アゼルバイジャン','country_name_e'=>'Azerbaijan','country_code_a3'=>'AZE','country_code_n3'=>'31','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AF','country_name_j'=>'アフガニスタン','country_name_e'=>'Afghanistan','country_code_a3'=>'AFG','country_code_n3'=>'4','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'US','country_name_j'=>'アメリカ合衆国','country_name_e'=>'United States of America','country_code_a3'=>'USA','country_code_n3'=>'840','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VI','country_name_j'=>'アメリカ領ヴァージン諸島','country_name_e'=>'Virgin Islands (U.S.)','country_code_a3'=>'VIR','country_code_n3'=>'850','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AS','country_name_j'=>'アメリカ領サモア','country_name_e'=>'American Samoa','country_code_a3'=>'ASM','country_code_n3'=>'16','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AE','country_name_j'=>'アラブ首長国連邦','country_name_e'=>'United Arab Emirates','country_code_a3'=>'ARE','country_code_n3'=>'784','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DZ','country_name_j'=>'アルジェリア','country_name_e'=>'Algeria','country_code_a3'=>'DZA','country_code_n3'=>'12','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AR','country_name_j'=>'アルゼンチン','country_name_e'=>'Argentina','country_code_a3'=>'ARG','country_code_n3'=>'32','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AW','country_name_j'=>'アルバ','country_name_e'=>'Aruba','country_code_a3'=>'ABW','country_code_n3'=>'533','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AL','country_name_j'=>'アルバニア','country_name_e'=>'Albania','country_code_a3'=>'ALB','country_code_n3'=>'8','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AM','country_name_j'=>'アルメニア','country_name_e'=>'Armenia','country_code_a3'=>'ARM','country_code_n3'=>'51','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AI','country_name_j'=>'アンギラ','country_name_e'=>'Anguilla','country_code_a3'=>'AIA','country_code_n3'=>'660','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AO','country_name_j'=>'アンゴラ','country_name_e'=>'Angola','country_code_a3'=>'AGO','country_code_n3'=>'24','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AG','country_name_j'=>'アンティグア・バーブーダ','country_name_e'=>'Antigua and Barbuda','country_code_a3'=>'ATG','country_code_n3'=>'28','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AD','country_name_j'=>'アンドラ','country_name_e'=>'Andorra','country_code_a3'=>'AND','country_code_n3'=>'20','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'YE','country_name_j'=>'イエメン','country_name_e'=>'Yemen','country_code_a3'=>'YEM','country_code_n3'=>'887','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GB','country_name_j'=>'イギリス','country_name_e'=>'United Kingdom of Great Britain and Northern Ireland','country_code_a3'=>'GBR','country_code_n3'=>'826','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IO','country_name_j'=>'イギリス領インド洋地域','country_name_e'=>'British Indian Ocean Territory','country_code_a3'=>'IOT','country_code_n3'=>'86','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VG','country_name_j'=>'イギリス領ヴァージン諸島','country_name_e'=>'Virgin Islands (British)','country_code_a3'=>'VGB','country_code_n3'=>'92','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IL','country_name_j'=>'イスラエル','country_name_e'=>'Israel','country_code_a3'=>'ISR','country_code_n3'=>'376','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IT','country_name_j'=>'イタリア','country_name_e'=>'Italy','country_code_a3'=>'ITA','country_code_n3'=>'380','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IQ','country_name_j'=>'イラク','country_name_e'=>'Iraq','country_code_a3'=>'IRQ','country_code_n3'=>'368','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IR','country_name_j'=>'イラン・イスラム共和国','country_name_e'=>'Iran (Islamic Republic of)','country_code_a3'=>'IRN','country_code_n3'=>'364','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IN','country_name_j'=>'インド','country_name_e'=>'India','country_code_a3'=>'IND','country_code_n3'=>'356','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ID','country_name_j'=>'インドネシア','country_name_e'=>'Indonesia','country_code_a3'=>'IDN','country_code_n3'=>'360','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'WF','country_name_j'=>'ウォリス・フツナ','country_name_e'=>'Wallis and Futuna','country_code_a3'=>'WLF','country_code_n3'=>'876','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'UG','country_name_j'=>'ウガンダ','country_name_e'=>'Uganda','country_code_a3'=>'UGA','country_code_n3'=>'800','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'UA','country_name_j'=>'ウクライナ','country_name_e'=>'Ukraine','country_code_a3'=>'UKR','country_code_n3'=>'804','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'UZ','country_name_j'=>'ウズベキスタン','country_name_e'=>'Uzbekistan','country_code_a3'=>'UZB','country_code_n3'=>'860','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'UY','country_name_j'=>'ウルグアイ','country_name_e'=>'Uruguay','country_code_a3'=>'URY','country_code_n3'=>'858','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'EC','country_name_j'=>'エクアドル','country_name_e'=>'Ecuador','country_code_a3'=>'ECU','country_code_n3'=>'218','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'EG','country_name_j'=>'エジプト','country_name_e'=>'Egypt','country_code_a3'=>'EGY','country_code_n3'=>'818','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'EE','country_name_j'=>'エストニア','country_name_e'=>'Estonia','country_code_a3'=>'EST','country_code_n3'=>'233','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SZ','country_name_j'=>'エスワティニ','country_name_e'=>'Eswatini','country_code_a3'=>'SWZ','country_code_n3'=>'748','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ET','country_name_j'=>'エチオピア','country_name_e'=>'Ethiopia','country_code_a3'=>'ETH','country_code_n3'=>'231','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ER','country_name_j'=>'エリトリア','country_name_e'=>'Eritrea','country_code_a3'=>'ERI','country_code_n3'=>'232','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SV','country_name_j'=>'エルサルバドル','country_name_e'=>'El Salvador','country_code_a3'=>'SLV','country_code_n3'=>'222','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AU','country_name_j'=>'オーストラリア','country_name_e'=>'Australia','country_code_a3'=>'AUS','country_code_n3'=>'36','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AT','country_name_j'=>'オーストリア','country_name_e'=>'Austria','country_code_a3'=>'AUT','country_code_n3'=>'40','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AX','country_name_j'=>'オーランド諸島','country_name_e'=>'Åland Islands','country_code_a3'=>'ALA','country_code_n3'=>'248','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'OM','country_name_j'=>'オマーン','country_name_e'=>'Oman','country_code_a3'=>'OMN','country_code_n3'=>'512','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NL','country_name_j'=>'オランダ','country_name_e'=>'Netherlands','country_code_a3'=>'NLD','country_code_n3'=>'528','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GH','country_name_j'=>'ガーナ','country_name_e'=>'Ghana','country_code_a3'=>'GHA','country_code_n3'=>'288','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CV','country_name_j'=>'カーボベルデ','country_name_e'=>'Cabo Verde','country_code_a3'=>'CPV','country_code_n3'=>'132','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GG','country_name_j'=>'ガーンジー','country_name_e'=>'Guernsey','country_code_a3'=>'GGY','country_code_n3'=>'831','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GY','country_name_j'=>'ガイアナ','country_name_e'=>'Guyana','country_code_a3'=>'GUY','country_code_n3'=>'328','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KZ','country_name_j'=>'カザフスタン','country_name_e'=>'Kazakhstan','country_code_a3'=>'KAZ','country_code_n3'=>'398','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'QA','country_name_j'=>'カタール','country_name_e'=>'Qatar','country_code_a3'=>'QAT','country_code_n3'=>'634','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'UM','country_name_j'=>'合衆国領有小離島','country_name_e'=>'United States Minor Outlying Islands','country_code_a3'=>'UMI','country_code_n3'=>'581','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CA','country_name_j'=>'カナダ','country_name_e'=>'Canada','country_code_a3'=>'CAN','country_code_n3'=>'124','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GA','country_name_j'=>'ガボン','country_name_e'=>'Gabon','country_code_a3'=>'GAB','country_code_n3'=>'266','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CM','country_name_j'=>'カメルーン','country_name_e'=>'Cameroon','country_code_a3'=>'CMR','country_code_n3'=>'120','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GM','country_name_j'=>'ガンビア','country_name_e'=>'Gambia','country_code_a3'=>'GMB','country_code_n3'=>'270','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KH','country_name_j'=>'カンボジア','country_name_e'=>'Cambodia','country_code_a3'=>'KHM','country_code_n3'=>'116','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MK','country_name_j'=>'北マケドニア','country_name_e'=>'North Macedonia','country_code_a3'=>'MKD','country_code_n3'=>'807','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MP','country_name_j'=>'北マリアナ諸島','country_name_e'=>'Northern Mariana Islands','country_code_a3'=>'MNP','country_code_n3'=>'580','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GN','country_name_j'=>'ギニア','country_name_e'=>'Guinea','country_code_a3'=>'GIN','country_code_n3'=>'324','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GW','country_name_j'=>'ギニアビサウ','country_name_e'=>'Guinea-Bissau','country_code_a3'=>'GNB','country_code_n3'=>'624','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CY','country_name_j'=>'キプロス','country_name_e'=>'Cyprus','country_code_a3'=>'CYP','country_code_n3'=>'196','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CU','country_name_j'=>'キューバ','country_name_e'=>'Cuba','country_code_a3'=>'CUB','country_code_n3'=>'192','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CW','country_name_j'=>'キュラソー','country_name_e'=>'Curaçao','country_code_a3'=>'CUW','country_code_n3'=>'531','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GR','country_name_j'=>'ギリシャ','country_name_e'=>'Greece','country_code_a3'=>'GRC','country_code_n3'=>'300','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KI','country_name_j'=>'キリバス','country_name_e'=>'Kiribati','country_code_a3'=>'KIR','country_code_n3'=>'296','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KG','country_name_j'=>'キルギス','country_name_e'=>'Kyrgyzstan','country_code_a3'=>'KGZ','country_code_n3'=>'417','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GT','country_name_j'=>'グアテマラ','country_name_e'=>'Guatemala','country_code_a3'=>'GTM','country_code_n3'=>'320','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GP','country_name_j'=>'グアドループ','country_name_e'=>'Guadeloupe','country_code_a3'=>'GLP','country_code_n3'=>'312','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GU','country_name_j'=>'グアム','country_name_e'=>'Guam','country_code_a3'=>'GUM','country_code_n3'=>'316','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KW','country_name_j'=>'クウェート','country_name_e'=>'Kuwait','country_code_a3'=>'KWT','country_code_n3'=>'414','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CK','country_name_j'=>'クック諸島','country_name_e'=>'Cook Islands','country_code_a3'=>'COK','country_code_n3'=>'184','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GL','country_name_j'=>'グリーンランド','country_name_e'=>'Greenland','country_code_a3'=>'GRL','country_code_n3'=>'304','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CX','country_name_j'=>'クリスマス島','country_name_e'=>'Christmas Island','country_code_a3'=>'CXR','country_code_n3'=>'162','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GD','country_name_j'=>'グレナダ','country_name_e'=>'Grenada','country_code_a3'=>'GRD','country_code_n3'=>'308','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HR','country_name_j'=>'クロアチア','country_name_e'=>'Croatia','country_code_a3'=>'HRV','country_code_n3'=>'191','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KY','country_name_j'=>'ケイマン諸島','country_name_e'=>'Cayman Islands','country_code_a3'=>'CYM','country_code_n3'=>'136','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KE','country_name_j'=>'ケニア','country_name_e'=>'Kenya','country_code_a3'=>'KEN','country_code_n3'=>'404','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CI','country_name_j'=>'コートジボワール','country_name_e'=>'Côte d Ivoire','country_code_a3'=>'CIV','country_code_n3'=>'384','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CC','country_name_j'=>'ココス諸島の旗 ココス（キーリング）諸島','country_name_e'=>'Cocos (Keeling) Islands','country_code_a3'=>'CCK','country_code_n3'=>'166','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CR','country_name_j'=>'コスタリカ','country_name_e'=>'Costa Rica','country_code_a3'=>'CRI','country_code_n3'=>'188','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KM','country_name_j'=>'コモロ','country_name_e'=>'Comoros','country_code_a3'=>'COM','country_code_n3'=>'174','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CO','country_name_j'=>'コロンビア','country_name_e'=>'Colombia','country_code_a3'=>'COL','country_code_n3'=>'170','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CG','country_name_j'=>'コンゴ共和国','country_name_e'=>'Congo','country_code_a3'=>'COG','country_code_n3'=>'178','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CD','country_name_j'=>'コンゴ民主共和国','country_name_e'=>'Congo, Democratic Republic of the','country_code_a3'=>'COD','country_code_n3'=>'180','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SA','country_name_j'=>'サウジアラビア','country_name_e'=>'Saudi Arabia','country_code_a3'=>'SAU','country_code_n3'=>'682','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GS','country_name_j'=>'サウスジョージア・サウスサンドウィッチ諸島','country_name_e'=>'South Georgia and the South Sandwich Islands','country_code_a3'=>'SGS','country_code_n3'=>'239','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'WS','country_name_j'=>'サモア','country_name_e'=>'Samoa','country_code_a3'=>'WSM','country_code_n3'=>'882','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ST','country_name_j'=>'サントメ・プリンシペ','country_name_e'=>'Sao Tome and Principe','country_code_a3'=>'STP','country_code_n3'=>'678','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BL','country_name_j'=>'サン・バルテルミー','country_name_e'=>'Saint Barthélemy','country_code_a3'=>'BLM','country_code_n3'=>'652','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ZM','country_name_j'=>'ザンビア','country_name_e'=>'Zambia','country_code_a3'=>'ZMB','country_code_n3'=>'894','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PM','country_name_j'=>'サンピエール島・ミクロン島','country_name_e'=>'Saint Pierre and Miquelon','country_code_a3'=>'SPM','country_code_n3'=>'666','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SM','country_name_j'=>'サンマリノ','country_name_e'=>'San Marino','country_code_a3'=>'SMR','country_code_n3'=>'674','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MF','country_name_j'=>'サン・マルタン（フランス領）','country_name_e'=>'Saint Martin (French part)','country_code_a3'=>'MAF','country_code_n3'=>'663','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SL','country_name_j'=>'シエラレオネ','country_name_e'=>'Sierra Leone','country_code_a3'=>'SLE','country_code_n3'=>'694','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DJ','country_name_j'=>'ジブチ','country_name_e'=>'Djibouti','country_code_a3'=>'DJI','country_code_n3'=>'262','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GI','country_name_j'=>'ジブラルタル','country_name_e'=>'Gibraltar','country_code_a3'=>'GIB','country_code_n3'=>'292','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'JE','country_name_j'=>'ジャージー','country_name_e'=>'Jersey','country_code_a3'=>'JEY','country_code_n3'=>'832','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'JM','country_name_j'=>'ジャマイカ','country_name_e'=>'Jamaica','country_code_a3'=>'JAM','country_code_n3'=>'388','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GE','country_name_j'=>'ジョージア','country_name_e'=>'Georgia','country_code_a3'=>'GEO','country_code_n3'=>'268','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SY','country_name_j'=>'シリア・アラブ共和国','country_name_e'=>'Syrian Arab Republic','country_code_a3'=>'SYR','country_code_n3'=>'760','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SG','country_name_j'=>'シンガポール','country_name_e'=>'Singapore','country_code_a3'=>'SGP','country_code_n3'=>'702','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SX','country_name_j'=>'シント・マールテン（オランダ領）','country_name_e'=>'Sint Maarten (Dutch part)','country_code_a3'=>'SXM','country_code_n3'=>'534','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ZW','country_name_j'=>'ジンバブエ','country_name_e'=>'Zimbabwe','country_code_a3'=>'ZWE','country_code_n3'=>'716','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CH','country_name_j'=>'スイス','country_name_e'=>'Switzerland','country_code_a3'=>'CHE','country_code_n3'=>'756','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SE','country_name_j'=>'スウェーデン','country_name_e'=>'Sweden','country_code_a3'=>'SWE','country_code_n3'=>'752','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SD','country_name_j'=>'スーダン','country_name_e'=>'Sudan','country_code_a3'=>'SDN','country_code_n3'=>'729','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SJ','country_name_j'=>'スヴァールバル諸島およびヤンマイエン島','country_name_e'=>'Svalbard and Jan Mayen','country_code_a3'=>'SJM','country_code_n3'=>'744','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ES','country_name_j'=>'スペイン','country_name_e'=>'Spain','country_code_a3'=>'ESP','country_code_n3'=>'724','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SR','country_name_j'=>'スリナム','country_name_e'=>'Suriname','country_code_a3'=>'SUR','country_code_n3'=>'740','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LK','country_name_j'=>'スリランカ','country_name_e'=>'Sri Lanka','country_code_a3'=>'LKA','country_code_n3'=>'144','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SK','country_name_j'=>'スロバキア','country_name_e'=>'Slovakia','country_code_a3'=>'SVK','country_code_n3'=>'703','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SI','country_name_j'=>'スロベニア','country_name_e'=>'Slovenia','country_code_a3'=>'SVN','country_code_n3'=>'705','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SC','country_name_j'=>'セーシェル','country_name_e'=>'Seychelles','country_code_a3'=>'SYC','country_code_n3'=>'690','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GQ','country_name_j'=>'赤道ギニア','country_name_e'=>'Equatorial Guinea','country_code_a3'=>'GNQ','country_code_n3'=>'226','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SN','country_name_j'=>'セネガル','country_name_e'=>'Senegal','country_code_a3'=>'SEN','country_code_n3'=>'686','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'RS','country_name_j'=>'セルビア','country_name_e'=>'Serbia','country_code_a3'=>'SRB','country_code_n3'=>'688','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KN','country_name_j'=>'セントクリストファー・ネイビス','country_name_e'=>'Saint Kitts and Nevis','country_code_a3'=>'KNA','country_code_n3'=>'659','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VC','country_name_j'=>'セントビンセント・グレナディーン','country_name_e'=>'Saint Vincent and the Grenadines','country_code_a3'=>'VCT','country_code_n3'=>'670','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SH','country_name_j'=>'セントヘレナ・アセンションおよびトリスタンダクーニャ','country_name_e'=>'Saint Helena, Ascension and Tristan da Cunha','country_code_a3'=>'SHN','country_code_n3'=>'654','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LC','country_name_j'=>'セントルシア','country_name_e'=>'Saint Lucia','country_code_a3'=>'LCA','country_code_n3'=>'662','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SO','country_name_j'=>'ソマリア','country_name_e'=>'Somalia','country_code_a3'=>'SOM','country_code_n3'=>'706','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SB','country_name_j'=>'ソロモン諸島','country_name_e'=>'Solomon Islands','country_code_a3'=>'SLB','country_code_n3'=>'90','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TC','country_name_j'=>'タークス・カイコス諸島','country_name_e'=>'Turks and Caicos Islands','country_code_a3'=>'TCA','country_code_n3'=>'796','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TH','country_name_j'=>'タイ','country_name_e'=>'Thailand','country_code_a3'=>'THA','country_code_n3'=>'764','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KR','country_name_j'=>'大韓民国','country_name_e'=>'Korea (the Republic of)','country_code_a3'=>'KOR','country_code_n3'=>'410','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TW','country_name_j'=>'台湾地区','country_name_e'=>'Taiwan, Province of China','country_code_a3'=>'TWN','country_code_n3'=>'158','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TJ','country_name_j'=>'タジキスタン','country_name_e'=>'Tajikistan','country_code_a3'=>'TJK','country_code_n3'=>'762','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TZ','country_name_j'=>'タンザニア','country_name_e'=>'Tanzania, United Republic of','country_code_a3'=>'TZA','country_code_n3'=>'834','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CZ','country_name_j'=>'チェコ','country_name_e'=>'Czechia','country_code_a3'=>'CZE','country_code_n3'=>'203','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TD','country_name_j'=>'チャド','country_name_e'=>'Chad','country_code_a3'=>'TCD','country_code_n3'=>'148','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CF','country_name_j'=>'中央アフリカ共和国','country_name_e'=>'Central African Republic','country_code_a3'=>'CAF','country_code_n3'=>'140','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CN','country_name_j'=>'中華人民共和国','country_name_e'=>'China','country_code_a3'=>'CHN','country_code_n3'=>'156','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TN','country_name_j'=>'チュニジア','country_name_e'=>'Tunisia','country_code_a3'=>'TUN','country_code_n3'=>'788','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'KP','country_name_j'=>'朝鮮民主主義人民共和国','country_name_e'=>'Korea (the Democratic People s Republic of)','country_code_a3'=>'PRK','country_code_n3'=>'408','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'CL','country_name_j'=>'チリ','country_name_e'=>'Chile','country_code_a3'=>'CHL','country_code_n3'=>'152','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TV','country_name_j'=>'ツバル','country_name_e'=>'Tuvalu','country_code_a3'=>'TUV','country_code_n3'=>'798','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DK','country_name_j'=>'デンマーク','country_name_e'=>'Denmark','country_code_a3'=>'DNK','country_code_n3'=>'208','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DE','country_name_j'=>'ドイツ','country_name_e'=>'Germany','country_code_a3'=>'DEU','country_code_n3'=>'276','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TG','country_name_j'=>'トーゴ','country_name_e'=>'Togo','country_code_a3'=>'TGO','country_code_n3'=>'768','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TK','country_name_j'=>'トケラウ','country_name_e'=>'Tokelau','country_code_a3'=>'TKL','country_code_n3'=>'772','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DO','country_name_j'=>'ドミニカ共和国','country_name_e'=>'Dominican Republic','country_code_a3'=>'DOM','country_code_n3'=>'214','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'DM','country_name_j'=>'ドミニカ国','country_name_e'=>'Dominica','country_code_a3'=>'DMA','country_code_n3'=>'212','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TT','country_name_j'=>'トリニダード・トバゴ','country_name_e'=>'Trinidad and Tobago','country_code_a3'=>'TTO','country_code_n3'=>'780','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TM','country_name_j'=>'トルクメニスタン','country_name_e'=>'Turkmenistan','country_code_a3'=>'TKM','country_code_n3'=>'795','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TR','country_name_j'=>'トルコ','country_name_e'=>'Turkey','country_code_a3'=>'TUR','country_code_n3'=>'792','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TO','country_name_j'=>'トンガ','country_name_e'=>'Tonga','country_code_a3'=>'TON','country_code_n3'=>'776','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NG','country_name_j'=>'ナイジェリア','country_name_e'=>'Nigeria','country_code_a3'=>'NGA','country_code_n3'=>'566','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NR','country_name_j'=>'ナウル','country_name_e'=>'Nauru','country_code_a3'=>'NRU','country_code_n3'=>'520','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NA','country_name_j'=>'ナミビア','country_name_e'=>'Namibia','country_code_a3'=>'NAM','country_code_n3'=>'516','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'AQ','country_name_j'=>'南極','country_name_e'=>'Antarctica','country_code_a3'=>'ATA','country_code_n3'=>'10','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NU','country_name_j'=>'ニウエ','country_name_e'=>'Niue','country_code_a3'=>'NIU','country_code_n3'=>'570','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NI','country_name_j'=>'ニカラグア','country_name_e'=>'Nicaragua','country_code_a3'=>'NIC','country_code_n3'=>'558','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NE','country_name_j'=>'ニジェール','country_name_e'=>'Niger','country_code_a3'=>'NER','country_code_n3'=>'562','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'JP','country_name_j'=>'日本','country_name_e'=>'Japan','country_code_a3'=>'JPN','country_code_n3'=>'392','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'EH','country_name_j'=>'西サハラ','country_name_e'=>'Western Sahara','country_code_a3'=>'ESH','country_code_n3'=>'732','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NC','country_name_j'=>'ニューカレドニア','country_name_e'=>'New Caledonia','country_code_a3'=>'NCL','country_code_n3'=>'540','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NZ','country_name_j'=>'ニュージーランド','country_name_e'=>'New Zealand','country_code_a3'=>'NZL','country_code_n3'=>'554','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NP','country_name_j'=>'ネパール','country_name_e'=>'Nepal','country_code_a3'=>'NPL','country_code_n3'=>'524','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NF','country_name_j'=>'ノーフォーク島','country_name_e'=>'Norfolk Island','country_code_a3'=>'NFK','country_code_n3'=>'574','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'NO','country_name_j'=>'ノルウェー','country_name_e'=>'Norway','country_code_a3'=>'NOR','country_code_n3'=>'578','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HM','country_name_j'=>'ハード島とマクドナルド諸島','country_name_e'=>'Heard Island and McDonald Islands','country_code_a3'=>'HMD','country_code_n3'=>'334','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BH','country_name_j'=>'バーレーン','country_name_e'=>'Bahrain','country_code_a3'=>'BHR','country_code_n3'=>'48','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HT','country_name_j'=>'ハイチ','country_name_e'=>'Haiti','country_code_a3'=>'HTI','country_code_n3'=>'332','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PK','country_name_j'=>'パキスタン','country_name_e'=>'Pakistan','country_code_a3'=>'PAK','country_code_n3'=>'586','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VA','country_name_j'=>'バチカン市国','country_name_e'=>'Holy See','country_code_a3'=>'VAT','country_code_n3'=>'336','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PA','country_name_j'=>'パナマ','country_name_e'=>'Panama','country_code_a3'=>'PAN','country_code_n3'=>'591','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VU','country_name_j'=>'バヌアツ','country_name_e'=>'Vanuatu','country_code_a3'=>'VUT','country_code_n3'=>'548','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BS','country_name_j'=>'バハマ','country_name_e'=>'Bahamas','country_code_a3'=>'BHS','country_code_n3'=>'44','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PG','country_name_j'=>'パプアニューギニア','country_name_e'=>'Papua New Guinea','country_code_a3'=>'PNG','country_code_n3'=>'598','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BM','country_name_j'=>'バミューダ','country_name_e'=>'Bermuda','country_code_a3'=>'BMU','country_code_n3'=>'60','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PW','country_name_j'=>'パラオ','country_name_e'=>'Palau','country_code_a3'=>'PLW','country_code_n3'=>'585','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PY','country_name_j'=>'パラグアイ','country_name_e'=>'Paraguay','country_code_a3'=>'PRY','country_code_n3'=>'600','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BB','country_name_j'=>'バルバドス','country_name_e'=>'Barbados','country_code_a3'=>'BRB','country_code_n3'=>'52','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PS','country_name_j'=>'パレスチナ','country_name_e'=>'Palestine, State of','country_code_a3'=>'PSE','country_code_n3'=>'275','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HU','country_name_j'=>'ハンガリー','country_name_e'=>'Hungary','country_code_a3'=>'HUN','country_code_n3'=>'348','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BD','country_name_j'=>'バングラデシュ','country_name_e'=>'Bangladesh','country_code_a3'=>'BGD','country_code_n3'=>'50','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TL','country_name_j'=>'東ティモール','country_name_e'=>'Timor-Leste','country_code_a3'=>'TLS','country_code_n3'=>'626','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PN','country_name_j'=>'ピトケアン','country_name_e'=>'Pitcairn','country_code_a3'=>'PCN','country_code_n3'=>'612','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FJ','country_name_j'=>'フィジー','country_name_e'=>'Fiji','country_code_a3'=>'FJI','country_code_n3'=>'242','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PH','country_name_j'=>'フィリピン','country_name_e'=>'Philippines','country_code_a3'=>'PHL','country_code_n3'=>'608','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FI','country_name_j'=>'フィンランド','country_name_e'=>'Finland','country_code_a3'=>'FIN','country_code_n3'=>'246','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BT','country_name_j'=>'ブータン','country_name_e'=>'Bhutan','country_code_a3'=>'BTN','country_code_n3'=>'64','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BV','country_name_j'=>'ブーベ島','country_name_e'=>'Bouvet Island','country_code_a3'=>'BVT','country_code_n3'=>'74','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PR','country_name_j'=>'プエルトリコ','country_name_e'=>'Puerto Rico','country_code_a3'=>'PRI','country_code_n3'=>'630','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FO','country_name_j'=>'フェロー諸島','country_name_e'=>'Faroe Islands','country_code_a3'=>'FRO','country_code_n3'=>'234','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FK','country_name_j'=>'フォークランド（マルビナス）諸島','country_name_e'=>'Falkland Islands (Malvinas)','country_code_a3'=>'FLK','country_code_n3'=>'238','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BR','country_name_j'=>'ブラジル','country_name_e'=>'Brazil','country_code_a3'=>'BRA','country_code_n3'=>'76','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FR','country_name_j'=>'フランス','country_name_e'=>'France','country_code_a3'=>'FRA','country_code_n3'=>'250','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'GF','country_name_j'=>'フランス領ギアナ','country_name_e'=>'French Guiana','country_code_a3'=>'GUF','country_code_n3'=>'254','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PF','country_name_j'=>'フランス領ポリネシア','country_name_e'=>'French Polynesia','country_code_a3'=>'PYF','country_code_n3'=>'258','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'TF','country_name_j'=>'フランス領南方・南極地域','country_name_e'=>'French Southern Territories','country_code_a3'=>'ATF','country_code_n3'=>'260','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BG','country_name_j'=>'ブルガリア','country_name_e'=>'Bulgaria','country_code_a3'=>'BGR','country_code_n3'=>'100','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BF','country_name_j'=>'ブルキナファソ','country_name_e'=>'Burkina Faso','country_code_a3'=>'BFA','country_code_n3'=>'854','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BN','country_name_j'=>'ブルネイ・ダルサラーム','country_name_e'=>'Brunei Darussalam','country_code_a3'=>'BRN','country_code_n3'=>'96','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BI','country_name_j'=>'ブルンジ','country_name_e'=>'Burundi','country_code_a3'=>'BDI','country_code_n3'=>'108','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VN','country_name_j'=>'ベトナム','country_name_e'=>'Viet Nam','country_code_a3'=>'VNM','country_code_n3'=>'704','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BJ','country_name_j'=>'ベナン','country_name_e'=>'Benin','country_code_a3'=>'BEN','country_code_n3'=>'204','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'VE','country_name_j'=>'ベネズエラ・ボリバル共和国','country_name_e'=>'Venezuela (Bolivarian Republic of)','country_code_a3'=>'VEN','country_code_n3'=>'862','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BY','country_name_j'=>'ベラルーシ','country_name_e'=>'Belarus','country_code_a3'=>'BLR','country_code_n3'=>'112','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BZ','country_name_j'=>'ベリーズ','country_name_e'=>'Belize','country_code_a3'=>'BLZ','country_code_n3'=>'84','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PE','country_name_j'=>'ペルー','country_name_e'=>'Peru','country_code_a3'=>'PER','country_code_n3'=>'604','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BE','country_name_j'=>'ベルギー','country_name_e'=>'Belgium','country_code_a3'=>'BEL','country_code_n3'=>'56','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PL','country_name_j'=>'ポーランド','country_name_e'=>'Poland','country_code_a3'=>'POL','country_code_n3'=>'616','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BA','country_name_j'=>'ボスニア・ヘルツェゴビナ','country_name_e'=>'Bosnia and Herzegovina','country_code_a3'=>'BIH','country_code_n3'=>'70','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BW','country_name_j'=>'ボツワナ','country_name_e'=>'Botswana','country_code_a3'=>'BWA','country_code_n3'=>'72','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BQ','country_name_j'=>'ボネール、シント・ユースタティウスおよびサバ','country_name_e'=>'Bonaire, Sint Eustatius and Saba','country_code_a3'=>'BES','country_code_n3'=>'535','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'BO','country_name_j'=>'ボリビア多民族国','country_name_e'=>'Bolivia (Plurinational State of)','country_code_a3'=>'BOL','country_code_n3'=>'68','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'PT','country_name_j'=>'ポルトガル','country_name_e'=>'Portugal','country_code_a3'=>'PRT','country_code_n3'=>'620','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HK','country_name_j'=>'香港','country_name_e'=>'Hong Kong','country_code_a3'=>'HKG','country_code_n3'=>'344','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'HN','country_name_j'=>'ホンジュラス','country_name_e'=>'Honduras','country_code_a3'=>'HND','country_code_n3'=>'340','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MH','country_name_j'=>'マーシャル諸島','country_name_e'=>'Marshall Islands','country_code_a3'=>'MHL','country_code_n3'=>'584','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MO','country_name_j'=>'マカオ','country_name_e'=>'Macau','country_code_a3'=>'MAC','country_code_n3'=>'446','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MG','country_name_j'=>'マダガスカル','country_name_e'=>'Madagascar','country_code_a3'=>'MDG','country_code_n3'=>'450','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'YT','country_name_j'=>'マヨット','country_name_e'=>'Mayotte','country_code_a3'=>'MYT','country_code_n3'=>'175','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MW','country_name_j'=>'マラウイ','country_name_e'=>'Malawi','country_code_a3'=>'MWI','country_code_n3'=>'454','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ML','country_name_j'=>'マリ','country_name_e'=>'Mali','country_code_a3'=>'MLI','country_code_n3'=>'466','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MT','country_name_j'=>'マルタ','country_name_e'=>'Malta','country_code_a3'=>'MLT','country_code_n3'=>'470','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MQ','country_name_j'=>'マルティニーク','country_name_e'=>'Martinique','country_code_a3'=>'MTQ','country_code_n3'=>'474','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MY','country_name_j'=>'マレーシア','country_name_e'=>'Malaysia','country_code_a3'=>'MYS','country_code_n3'=>'458','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'IM','country_name_j'=>'マン島','country_name_e'=>'Isle of Man','country_code_a3'=>'IMN','country_code_n3'=>'833','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'FM','country_name_j'=>'ミクロネシア連邦','country_name_e'=>'Micronesia (Federated States of)','country_code_a3'=>'FSM','country_code_n3'=>'583','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ZA','country_name_j'=>'南アフリカ','country_name_e'=>'South Africa','country_code_a3'=>'ZAF','country_code_n3'=>'710','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'SS','country_name_j'=>'南スーダン','country_name_e'=>'South Sudan','country_code_a3'=>'SSD','country_code_n3'=>'728','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MM','country_name_j'=>'ミャンマー','country_name_e'=>'Myanmar','country_code_a3'=>'MMR','country_code_n3'=>'104','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MX','country_name_j'=>'メキシコ','country_name_e'=>'Mexico','country_code_a3'=>'MEX','country_code_n3'=>'484','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MU','country_name_j'=>'モーリシャス','country_name_e'=>'Mauritius','country_code_a3'=>'MUS','country_code_n3'=>'480','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MR','country_name_j'=>'モーリタニア','country_name_e'=>'Mauritania','country_code_a3'=>'MRT','country_code_n3'=>'478','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MZ','country_name_j'=>'モザンビーク','country_name_e'=>'Mozambique','country_code_a3'=>'MOZ','country_code_n3'=>'508','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MC','country_name_j'=>'モナコ','country_name_e'=>'Monaco','country_code_a3'=>'MCO','country_code_n3'=>'492','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MV','country_name_j'=>'モルディブ','country_name_e'=>'Maldives','country_code_a3'=>'MDV','country_code_n3'=>'462','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MD','country_name_j'=>'モルドバ共和国','country_name_e'=>'Moldova, Republic of','country_code_a3'=>'MDA','country_code_n3'=>'498','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MA','country_name_j'=>'モロッコ','country_name_e'=>'Morocco','country_code_a3'=>'MAR','country_code_n3'=>'504','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MN','country_name_j'=>'モンゴル','country_name_e'=>'Mongolia','country_code_a3'=>'MNG','country_code_n3'=>'496','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'ME','country_name_j'=>'モンテネグロ','country_name_e'=>'Montenegro','country_code_a3'=>'MNE','country_code_n3'=>'499','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'MS','country_name_j'=>'モントセラト','country_name_e'=>'Montserrat','country_code_a3'=>'MSR','country_code_n3'=>'500','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'JO','country_name_j'=>'ヨルダン','country_name_e'=>'Jordan','country_code_a3'=>'JOR','country_code_n3'=>'400','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LA','country_name_j'=>'ラオス人民民主共和国','country_name_e'=>'Lao People s Democratic Republic','country_code_a3'=>'LAO','country_code_n3'=>'418','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LV','country_name_j'=>'ラトビア','country_name_e'=>'Latvia','country_code_a3'=>'LVA','country_code_n3'=>'428','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LT','country_name_j'=>'リトアニア','country_name_e'=>'Lithuania','country_code_a3'=>'LTU','country_code_n3'=>'440','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LY','country_name_j'=>'リビア','country_name_e'=>'Libya','country_code_a3'=>'LBY','country_code_n3'=>'434','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LI','country_name_j'=>'リヒテンシュタイン','country_name_e'=>'Liechtenstein','country_code_a3'=>'LIE','country_code_n3'=>'438','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LR','country_name_j'=>'リベリア','country_name_e'=>'Liberia','country_code_a3'=>'LBR','country_code_n3'=>'430','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'RO','country_name_j'=>'ルーマニア','country_name_e'=>'Romania','country_code_a3'=>'ROU','country_code_n3'=>'642','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LU','country_name_j'=>'ルクセンブルク','country_name_e'=>'Luxembourg','country_code_a3'=>'LUX','country_code_n3'=>'442','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'RW','country_name_j'=>'ルワンダ','country_name_e'=>'Rwanda','country_code_a3'=>'RWA','country_code_n3'=>'646','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LS','country_name_j'=>'レソト','country_name_e'=>'Lesotho','country_code_a3'=>'LSO','country_code_n3'=>'426','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'LB','country_name_j'=>'レバノン','country_name_e'=>'Lebanon','country_code_a3'=>'LBN','country_code_n3'=>'422','created_by'=>'admin','changed_by'=>'admin',]);
        Country::create(['country_code'=>'RE','country_name_j'=>'レユニオン','country_name_e'=>'Réunion','country_code_a3'=>'REU','country_code_n3'=>'638','created_by'=>'admin','changed_by'=>'admin',]);
    }
}
