<?php

namespace Database\Seeders\Masters;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Masters\Material;

class MaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Material::create(['material_code'=>'sample01','material_name'=>'レッツ','class_code'=>'001','model'=>'UZ50M1','engine'=>'49','coo'=>'JP','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'Y2W','color_code02'=>'PSE','color_code03'=>'W9K','color_code04'=>'30H','color_code05'=>'','color_name01'=>'パーセクブルーNo.4','color_name02'=>'サンディベージュ','color_name03'=>'ブラヴォドブラック','color_name04'=>'ソリッドスペシャルホワイトNo.2','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample02','material_name'=>'アドレスＶ５０','class_code'=>'001','model'=>'UZ50XM1','engine'=>'49','coo'=>'JP','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'YUA','color_code02'=>'YWG','color_code03'=>'YDG','color_code04'=>'YGS','color_code05'=>'','color_name01'=>'マットステラブルーメタリック','color_name02'=>'グラスミッドナイトブラウン','color_name03'=>'スプラッシュホワイト ','color_name04'=>'グラスシャインブラック ','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample03','material_name'=>'レッツバスケット','class_code'=>'001','model'=>'UZ0BM1','engine'=>'49','coo'=>'JP','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'YWG','color_code02'=>'30H','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'グラスミッドナイトブラウン','color_name02'=>'ソリッドスペシャルホワイトNo.2','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample04','material_name'=>'アドレス１２５','class_code'=>'001','model'=>'UZ125NEYM3','engine'=>'124','coo'=>'CN','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'QTZ','color_code02'=>'QMV','color_code03'=>'YPA','color_code04'=>'YKV','color_code05'=>'','color_name01'=>'ダークグリーニッシュブルーメタリック','color_name02'=>'マットボルドーレッドメタリック','color_name03'=>'パールミラージュホワイト','color_name04'=>'マットブラックメタリックNo.2','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample05','material_name'=>'アヴェニス１２５','class_code'=>'001','model'=>'UN125NEM3','engine'=>'124','coo'=>'ID','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'A8D','color_code02'=>'CC8','color_code03'=>'KGL','color_code04'=>'','color_code05'=>'','color_name01'=>'パールミラージュホワイト/マットフィブロイングレーメタリック','color_name02'=>'マットフィブロイングレーメタリック/ラッシュグリーンメタリック','color_name03'=>'グラススパークルブラック/マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample06','material_name'=>'バーグマンストリート１２５ＥＸ【M6】','class_code'=>'001','model'=>'UB125LNMM6','engine'=>'124','coo'=>'ID','unit'=>'UN','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'YUA','color_code02'=>'Q1S','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'マットステラブルーメタリック','color_name02'=>'パールグレイスホワイト','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample07','material_name'=>'ＧＳＸ－Ｓ１２５','class_code'=>'001','model'=>'GSX-S125LXM3','engine'=>'124','coo'=>'ID','unit'=>'UN','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'BGY','color_code02'=>'YVU','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック / タイタンブラック','color_name02'=>'タイタンブラック','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample08','material_name'=>'ＧＳＸ－Ｒ１２５','class_code'=>'001','model'=>'GSX-R125RLMM3','engine'=>'124','coo'=>'ID','unit'=>'UN','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'01','color_code01'=>'YSF','color_code02'=>'GTA','color_code03'=>'YVU','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック','color_name02'=>'ストロンガーレッド/タイタンブラック','color_name03'=>'タイタンブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample09','material_name'=>'ジクサー１５０【M3】','class_code'=>'001','model'=>'GSX150RLM3','engine'=>'154','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'YVB','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'グラススパークルブラック','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample10','material_name'=>'ジクサー１５０(青/白)','class_code'=>'001','model'=>'GSX150RLXM5','engine'=>'154','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'C0T','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'マットスティールグリーンメタリック/グラススパークルブラック','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample11','material_name'=>'ジクサー１５０','class_code'=>'001','model'=>'GSX150RLM5','engine'=>'154','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'CVS','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'オールトグレーメタリック/ラッシュグリーンメタリック','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample12','material_name'=>'ジクサー２５０【M3】','class_code'=>'001','model'=>'GSX250RLM3','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'YUA','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'マットステラブルーメタリック','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample13','material_name'=>'ジクサー２５０(青/白)','class_code'=>'001','model'=>'GSX250RLXM5','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample14','material_name'=>'ジクサー２５０','class_code'=>'001','model'=>'GSX250RLM5','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'CUU','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'マットボルドーレッドメタリック/マットブラックメタリックNo.2','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample15','material_name'=>'ジクサーＳＦ２５０【M3】','class_code'=>'001','model'=>'GSX250FRLM3','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'YUA','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'マットステラブルーメタリック','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample16','material_name'=>'ジクサーＳＦ２５０(青/白)','class_code'=>'001','model'=>'GSX250FRLXM5','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample17','material_name'=>'ジクサーＳＦ２５０','class_code'=>'001','model'=>'GSX250FRLM5','engine'=>'249','coo'=>'IN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'AGQ','color_code02'=>'CUU','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック/パールグレッシャーホワイト','color_name02'=>'マットボルドーレッドメタリック/マットブラックメタリックNo.2','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample18','material_name'=>'ＧＳＸ２５０Ｒ（通常色）','class_code'=>'001','model'=>'GSX250RRLJM4','engine'=>'248','coo'=>'ID','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'BKJ','color_code02'=>'4CX','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'ダイヤモンドレッドメタリック/ パールネブラーブラック','color_name02'=>'パールネブラーブラック','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample19','material_name'=>'ＧＳＸ２５０Ｒ（レースデカール）','class_code'=>'001','model'=>'GSX250RRLZM4','engine'=>'248','coo'=>'ID','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'CXX','color_code02'=>'CYX','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリックNo.2','color_name02'=>'パールグレッシャーホワイトNo.2','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample20','material_name'=>'Ｖストローム２５０','class_code'=>'001','model'=>'DL250RLJM4','engine'=>'248','coo'=>'CN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'CZX','color_code02'=>'BKJ','color_code03'=>'C0X','color_code04'=>'CKN','color_code05'=>'','color_name01'=>'ソリッドダズリンクールイエロー/ パールネブラーブラック','color_name02'=>'ダイヤモンドレッドメタリック/ パールネブラーブラック','color_name03'=>'ハイテックシルバーメタリック/ パールネブラーブラック','color_name04'=>'マットフラッシュブラックメタリック/ パールネブラーブラック','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample21','material_name'=>'Ｖストローム２５０ＳＸ','class_code'=>'001','model'=>'DS250RLM5','engine'=>'249','coo'=>'CN','unit'=>'UN','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ex'=>'02','type_zr_moto'=>'02','color_code01'=>'YU1','color_code02'=>'QSB','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'チャンピオンイエローNo.2','color_name02'=>'ソノマレッドメタリック','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample22','material_name'=>'バーグマン４００','class_code'=>'001','model'=>'AN400AM5','engine'=>'399','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'02','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'QKA','color_code02'=>'YUD','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'マットソードシルバーメタリック','color_name02'=>'ソリッドアイアングレー','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample23','material_name'=>'ＳＶ６５０','class_code'=>'001','model'=>'SV650AM5','engine'=>'645','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'03','type_cr1_2'=>'03','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'CGJ','color_code02'=>'C2L','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'パールビガーブルー/マットブラックメタリックNo.2','color_name02'=>'パールマットシャドーグリーン/マットブラックメタリックNo.2','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample24','material_name'=>'ＳＶ６５０Ｘ','class_code'=>'001','model'=>'SA650XAM5','engine'=>'645','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'03','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'QU2','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'パールテックホワイト','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample25','material_name'=>'Ｖストローム６５０','class_code'=>'001','model'=>'DL650AM5','engine'=>'645','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'03','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YKY','color_code02'=>'YVB','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'パールビガーブルー','color_name02'=>'グラススパークルブラック','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample26','material_name'=>'Ｖストローム６５０ＸＴ','class_code'=>'001','model'=>'DL650XAM5','engine'=>'645','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'03','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YU1','color_code02'=>'JWN','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'チャンピオンイエローNo.2','color_name02'=>'ブリリアントホワイト/パールビガーブルー','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample27','material_name'=>'Ｖストローム１０５０','class_code'=>'001','model'=>'DL1050RRM5','engine'=>'1036','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'BN8','color_code02'=>'CWY','color_code03'=>'C4X','color_code04'=>'','color_code05'=>'','color_name01'=>'オールトグレーメタリックNo.3/マットブラックメタリックNo.2','color_name02'=>'マットスティールグリーンメタリック/マットブラックメタリックNo.2','color_name03'=>'グラススパークルブラック/マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample28','material_name'=>'Ｖストローム１０５０ＤＥ','class_code'=>'001','model'=>'DL1050RJM5','engine'=>'1036','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'BT1','color_code02'=>'CK6','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'チャンピオンイエローNo.2/グラススパークルブラック','color_name02'=>'パールテックホワイト/グラススパークルブラック','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample29','material_name'=>'Ｖストローム８００','class_code'=>'001','model'=>'DL800RQM5','engine'=>'775','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'QEB','color_code02'=>'YYG','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'オールトグレーメタリックNo.3','color_name02'=>'キャンディダーリングレッド','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample30','material_name'=>'Ｖストローム８００ＤＥ','class_code'=>'001','model'=>'DL800DERCM5','engine'=>'775','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YU2','color_code02'=>'QU3','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'','color_name02'=>'','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample31','material_name'=>'ＧＳＸ－８Ｓ','class_code'=>'001','model'=>'GSX800RQM5','engine'=>'775','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'CLB','color_code02'=>'CL9','color_code03'=>'4UX','color_code04'=>'','color_code05'=>'','color_name01'=>'パールコズミックブルー/グラススパークルブラック','color_name02'=>'マットソードシルバーメタリック/ マットブラックメタリックNo.2','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample32','material_name'=>'ＧＳＸ－８Ｒ','class_code'=>'001','model'=>'GSX800FRQM5','engine'=>'775','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YSF','color_code02'=>'QKA','color_code03'=>'YKV','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック','color_name02'=>'マットソードシルバーメタリック','color_name03'=>'マットブラックメタリックNo.2','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample33','material_name'=>'ＧＳＸ－Ｓ１０００','class_code'=>'001','model'=>'GSX-S1000RQM5','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'03','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'6CX','color_code02'=>'CSX','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック','color_name02'=>'マットソードシルバーメタリック','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample34','material_name'=>'ＫＡＴＡＮＡ','class_code'=>'001','model'=>'GSX-S1000SRQM5','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YMD','color_code02'=>'YKY','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'ミスティックシルバーメタリック','color_name02'=>'パールビガーブルー','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample35','material_name'=>'ＧＳＸ－Ｓ１０００ＧＴ【M4】','class_code'=>'001','model'=>'GSX-S1000TRQM4','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YYG','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'キャンディダーリングレッド','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample36','material_name'=>'ＧＳＸ－Ｓ１０００ＧＴ','class_code'=>'001','model'=>'GSX-S1000TRQM5','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YKY','color_code02'=>'YYG','color_code03'=>'QEB','color_code04'=>'','color_code05'=>'','color_name01'=>'パールビガーブルー','color_name02'=>'キャンディダーリングレッド','color_name03'=>'オールトグレーメタリックNo.3','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample37','material_name'=>'ＧＳＸ－Ｓ１０００ＧＸ【M4】','class_code'=>'001','model'=>'GSX-S1000XRREM4','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YSF','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample38','material_name'=>'ＧＳＸ－Ｓ１０００ＧＸ','class_code'=>'001','model'=>'GSX-S1000XRREM5','engine'=>'998','coo'=>'JP','unit'=>'UN','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'YSF','color_code02'=>'YYG','color_code03'=>'YVB','color_code04'=>'','color_code05'=>'','color_name01'=>'トリトンブルーメタリック','color_name02'=>'キャンディダーリングレッド','color_name03'=>'グラススパークルブラック','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample39','material_name'=>'隼ＨＡＹＡＢＵＳＡ','class_code'=>'001','model'=>'GSX1300RRQM5','engine'=>'1339','coo'=>'JP','unit'=>'UN','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'C0T','color_code02'=>'BLG','color_code03'=>'ASU','color_code04'=>'','color_code05'=>'','color_name01'=>'マットスティールグリーンメタリック/グラススパークルブラック','color_name02'=>'グラススパークルブラック/マットチタニウムシルバーメタリック','color_name03'=>'ミスティックシルバーメタリック/パールビガーブルー','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Material::create(['material_code'=>'sample40','material_name'=>'隼ＨＡＹＡＢＵＳＡ　カラーオーダー','class_code'=>'001','model'=>'GSX1300RRQKM5','engine'=>'1339','coo'=>'JP','unit'=>'UN','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ex'=>'01','type_zr_moto'=>'02','color_code01'=>'','color_code02'=>'','color_code03'=>'','color_code04'=>'','color_code05'=>'','color_name01'=>'','color_name02'=>'','color_name03'=>'','color_name04'=>'','color_name05'=>'','text_material'=>'','remarks_material'=>'','created_by'=>'admin','changed_by'=>'admin',]);
    }
}
