<?php

namespace Database\Seeders\Transactions;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Transactions\Inventory;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－８Ｒ','model'=>'GSX800FRQM5','color_code'=>'QKA','color_name1'=>'マットソードシルバーメタリック','color_name2'=>'シルバー','body_number'=>'EM1AA-103460','doc_date'=>'2025-03-31','quantity'=>'1','unit'=>'UN','maker_price'=>'1090000','gross_price'=>'915600','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－８Ｒ【M4】','model'=>'GSX800FRQM4','color_code'=>'YSF','color_name1'=>'トリトンブルーメタリック','color_name2'=>'ブルー','body_number'=>'EM1AA-101499','doc_date'=>'2024-02-26','quantity'=>'1','unit'=>'UN','maker_price'=>'0','gross_price'=>'863200','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－８Ｓ','model'=>'GSX800RQM5','color_code'=>'CLB','color_name1'=>'パールコズミックブルー/グラススパークルブラック','color_name2'=>'ブルー/ブラック','body_number'=>'EM1AA-103299','doc_date'=>'2025-03-10','quantity'=>'1','unit'=>'UN','maker_price'=>'1020000','gross_price'=>'856800','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'02','type_cr1_2'=>'04','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｒ１２５','model'=>'GSX-R125RLMM3','color_code'=>'YVU','color_name1'=>'タイタンブラック','color_name2'=>'ブラック','body_number'=>'DL32D-100175','doc_date'=>'2022-08-30','quantity'=>'1','unit'=>'UN','maker_price'=>'412000','gross_price'=>'331100','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｒ１２５','model'=>'GSX-R125RLMM3','color_code'=>'YSF','color_name1'=>'トリトンブルーメタリック','color_name2'=>'ブルー','body_number'=>'DL32D-101481','doc_date'=>'2025-02-14','quantity'=>'1','unit'=>'UN','maker_price'=>'412000','gross_price'=>'319000','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｒ１２５','model'=>'GSX-R125RLMM3','color_code'=>'YVU','color_name1'=>'タイタンブラック','color_name2'=>'ブラック','body_number'=>'DL32D-101328','doc_date'=>'2025-03-24','quantity'=>'1','unit'=>'UN','maker_price'=>'412000','gross_price'=>'279000','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｒ１２５','model'=>'GSX-R125RLMM3','color_code'=>'GTA','color_name1'=>'ストロンガーレッド/タイタンブラック','color_name2'=>'レッド/ブラック','body_number'=>'DL32D-101737','doc_date'=>'2025-03-24','quantity'=>'1','unit'=>'UN','maker_price'=>'412000','gross_price'=>'279000','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１０００ＧＴ','model'=>'GSX-S1000TRQM5','color_code'=>'YYG','color_name1'=>'キャンディダーリングレッド','color_name2'=>'レッド','body_number'=>'EK1AA-104731','doc_date'=>'2024-10-04','quantity'=>'1','unit'=>'UN','maker_price'=>'1500000','gross_price'=>'1188000','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１０００ＧＸ','model'=>'GSX-S1000XRREM5','color_code'=>'YSF','color_name1'=>'トリトンブルーメタリック','color_name2'=>'ブルー','body_number'=>'EK1AA-104410','doc_date'=>'2024-04-08','quantity'=>'1','unit'=>'UN','maker_price'=>'1870000','gross_price'=>'1520400','type_dlv'=>'05','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'01','type_cr1_2'=>'04','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１２５','model'=>'GSX-S125LXM3','color_code'=>'BGY','color_name1'=>'トリトンブルーメタリック / タイタンブラック','color_name2'=>'ブルー/ブラック','body_number'=>'DL32D-502355','doc_date'=>'2025-02-14','quantity'=>'1','unit'=>'UN','maker_price'=>'382000','gross_price'=>'276000','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１２５','model'=>'GSX-S125LXM3','color_code'=>'YVU','color_name1'=>'タイタンブラック','color_name2'=>'ブラック','body_number'=>'DL32D-502277','doc_date'=>'2025-02-14','quantity'=>'1','unit'=>'UN','maker_price'=>'382000','gross_price'=>'276000','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１２５','model'=>'GSX-S125LXM3','color_code'=>'YVU','color_name1'=>'タイタンブラック','color_name2'=>'ブラック','body_number'=>'DL32D-502326','doc_date'=>'2025-05-09','quantity'=>'1','unit'=>'UN','maker_price'=>'382000','gross_price'=>'0','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＧＳＸ－Ｓ１２５','model'=>'GSX-S125LXM3','color_code'=>'YVU','color_name1'=>'タイタンブラック','color_name2'=>'ブラック','body_number'=>'DL32D-502416','doc_date'=>'2025-05-09','quantity'=>'1','unit'=>'UN','maker_price'=>'382000','gross_price'=>'0','type_dlv'=>'02','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ＳＶ６５０','model'=>'SV650AM5','color_code'=>'YKV','color_name1'=>'マットブラックメタリックNo.2','color_name2'=>'マットブラック','body_number'=>'VP55E-103433','doc_date'=>'2025-01-27','quantity'=>'1','unit'=>'UN','maker_price'=>'760000','gross_price'=>'638400','type_dlv'=>'04','type_cali'=>'03','type_theft'=>'02','type_cr1_1'=>'03','type_cr1_2'=>'03','type_zr_ext'=>'01','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'Ｖストローム２５０ＳＸ','model'=>'DS250RLM5','color_code'=>'QSB','color_name1'=>'ソノマレッドメタリック','color_name2'=>'レッド','body_number'=>'EL11L-104834','doc_date'=>'2024-12-20','quantity'=>'1','unit'=>'UN','maker_price'=>'538000','gross_price'=>'451900','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'CC8','color_name1'=>'マットフィブロイングレーメタリック/ラッシュグリーンメタリック','color_name2'=>'マットグレー/グリーン','body_number'=>'EA12J-104391','doc_date'=>'2024-06-14','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'202600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'A8D','color_name1'=>'パールミラージュホワイト/マットフィブロイングレーメタリック','color_name2'=>'ホワイト/マットグレー','body_number'=>'EA12J-106292','doc_date'=>'2024-09-11','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'202600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'A8D','color_name1'=>'パールミラージュホワイト/マットフィブロイングレーメタリック','color_name2'=>'ホワイト/マットグレー','body_number'=>'EA12J-106292','doc_date'=>'2024-09-13','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'202600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'KGL','color_name1'=>'グラススパークルブラック/マットブラックメタリックNo.2','color_name2'=>'ブラック/マットブラック','body_number'=>'EA12J-105929','doc_date'=>'2024-09-27','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'202600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'YDG','color_name1'=>'スプラッシュホワイト ','color_name2'=>'ホワイト','body_number'=>'EA12J-107064','doc_date'=>'2025-04-04','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'202600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アヴェニス１２５','model'=>'UN125NEM3','color_code'=>'CC8','color_name1'=>'マットフィブロイングレーメタリック/ラッシュグリーンメタリック','color_name2'=>'マットグレー/グリーン','body_number'=>'UN125-107364','doc_date'=>'2025-05-09','quantity'=>'1','unit'=>'UN','maker_price'=>'259000','gross_price'=>'0','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'QMV','color_name1'=>'マットボルドーレッドメタリック','color_name2'=>'マットレッド','body_number'=>'DP12H-102061','doc_date'=>'2023-02-03','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'209200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'QTZ','color_name1'=>'ダークグリーニッシュブルーメタリック','color_name2'=>'ブルー','body_number'=>'DP12H-107919','doc_date'=>'2024-08-09','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'194200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'YPA','color_name1'=>'パールミラージュホワイト','color_name2'=>'ホワイト','body_number'=>'DP12H-109446','doc_date'=>'2025-02-07','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'194200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'YPA','color_name1'=>'パールミラージュホワイト','color_name2'=>'ホワイト','body_number'=>'DP12H-109288','doc_date'=>'2025-02-07','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'194200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'QTZ','color_name1'=>'ダークグリーニッシュブルーメタリック','color_name2'=>'ブルー','body_number'=>'DP12H-109555','doc_date'=>'2025-02-14','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'194200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレス１２５','model'=>'UZ125NEYM3','color_code'=>'YPA','color_name1'=>'パールミラージュホワイト','color_name2'=>'ホワイト','body_number'=>'DP12H-109425','doc_date'=>'2025-02-21','quantity'=>'1','unit'=>'UN','maker_price'=>'249000','gross_price'=>'194200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'01','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YUA','color_name1'=>'マットステラブルーメタリック','color_name2'=>'マットブルー','body_number'=>'CA4BA-140960','doc_date'=>'2024-10-25','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YGS','color_name1'=>'グラスシャインブラック ','color_name2'=>'ブラック','body_number'=>'CA4BA-141185','doc_date'=>'2024-11-22','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YDG','color_name1'=>'スプラッシュホワイト ','color_name2'=>'ホワイト','body_number'=>'CA4BA-141351','doc_date'=>'2024-12-13','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YUA','color_name1'=>'マットステラブルーメタリック','color_name2'=>'マットブルー','body_number'=>'CA4BA-141541','doc_date'=>'2024-12-23','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YWG','color_name1'=>'グラスミッドナイトブラウン','color_name2'=>'ブラウン','body_number'=>'CA4BA-141571','doc_date'=>'2024-12-27','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YGS','color_name1'=>'グラスシャインブラック ','color_name2'=>'ブラック','body_number'=>'CA4BA-142001','doc_date'=>'2025-02-21','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YDG','color_name1'=>'スプラッシュホワイト ','color_name2'=>'ホワイト','body_number'=>'CA4BA-142187','doc_date'=>'2025-03-07','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YWG','color_name1'=>'グラスミッドナイトブラウン','color_name2'=>'ブラウン','body_number'=>'CA4BA-142391','doc_date'=>'2025-03-24','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YUA','color_name1'=>'マットステラブルーメタリック','color_name2'=>'マットブルー','body_number'=>'CA4BA-142295','doc_date'=>'2025-04-04','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'アドレスＶ５０','model'=>'UZ50XM1','color_code'=>'YDG','color_name1'=>'スプラッシュホワイト ','color_name2'=>'ホワイト','body_number'=>'CA4BA-142452','doc_date'=>'2025-04-10','quantity'=>'1','unit'=>'UN','maker_price'=>'176000','gross_price'=>'142600','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサー１５０【M3】','model'=>'GSX150RLM3','color_code'=>'YVB','color_name1'=>'グラススパークルブラック','color_name2'=>'ブラック','body_number'=>'ED131-100359','doc_date'=>'2023-01-27','quantity'=>'1','unit'=>'UN','maker_price'=>'350000','gross_price'=>'290500','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサー２５０','model'=>'GSX250RLM5','color_code'=>'CUU','color_name1'=>'マットボルドーレッドメタリック/マットブラックメタリックNo.2','color_name2'=>'マットレッド/マットブラック','body_number'=>'ED22Y-104802','doc_date'=>'2025-03-21','quantity'=>'1','unit'=>'UN','maker_price'=>'438000','gross_price'=>'367900','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサー２５０【M3】','model'=>'GSX250RLM3','color_code'=>'YKV','color_name1'=>'マットブラックメタリックNo.2','color_name2'=>'マットブラック','body_number'=>'ED22Y-103594','doc_date'=>'2024-08-30','quantity'=>'1','unit'=>'UN','maker_price'=>'438000','gross_price'=>'327900','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサー２５０【M3】','model'=>'GSX250RLM3','color_code'=>'YUA','color_name1'=>'マットステラブルーメタリック','color_name2'=>'マットブルー','body_number'=>'ED22Y-104495','doc_date'=>'2025-02-25','quantity'=>'1','unit'=>'UN','maker_price'=>'438000','gross_price'=>'327900','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'03','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサーＳＦ２５０【M3】','model'=>'GSX250FRLM3','color_code'=>'YKV','color_name1'=>'マットブラックメタリックNo.2','color_name2'=>'マットブラック','body_number'=>'ED22Y-103722','doc_date'=>'2025-01-31','quantity'=>'1','unit'=>'UN','maker_price'=>'468000','gross_price'=>'353100','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサーＳＦ２５０【M3】','model'=>'GSX250FRLM3','color_code'=>'YKV','color_name1'=>'マットブラックメタリックNo.2','color_name2'=>'マットブラック','body_number'=>'ED22Y-104568','doc_date'=>'2025-03-20','quantity'=>'1','unit'=>'UN','maker_price'=>'468000','gross_price'=>'353100','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'ジクサーＳＦ２５０【M3】','model'=>'GSX250FRLM3','color_code'=>'YKV','color_name1'=>'マットブラックメタリックNo.2','color_name2'=>'マットブラック','body_number'=>'ED22Y-101868','doc_date'=>'2025-04-22','quantity'=>'1','unit'=>'UN','maker_price'=>'468000','gross_price'=>'353120','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'バーグマンストリート１２５ＥＸ','model'=>'','color_code'=>'YPA','color_name1'=>'パールミラージュホワイト','color_name2'=>'ホワイト','body_number'=>'EA23M-106937','doc_date'=>'2025-02-28','quantity'=>'1','unit'=>'UN','maker_price'=>'0','gross_price'=>'227800','type_dlv'=>'03','type_cali'=>'02','type_theft'=>'02','type_cr1_1'=>'04','type_cr1_2'=>'04','type_zr_ext'=>'02','type_zr_moto'=>'02','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-247456','doc_date'=>'2024-01-12','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-248126','doc_date'=>'2024-02-06','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'Y2W','color_name1'=>'パーセクブルーNo.4','color_name2'=>'ブルー','body_number'=>'CA4AA-253767','doc_date'=>'2024-08-26','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'Y2W','color_name1'=>'パーセクブルーNo.4','color_name2'=>'ブルー','body_number'=>'CA4AA-254642','doc_date'=>'2024-09-20','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-254999','doc_date'=>'2024-10-01','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'PSE','color_name1'=>'サンディベージュ','color_name2'=>'ベージュ','body_number'=>'CA4AA-255327','doc_date'=>'2024-10-08','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'W9K','color_name1'=>'ブラヴォドブラック','color_name2'=>'ブラック','body_number'=>'CA4AA-255814','doc_date'=>'2024-10-29','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-258399','doc_date'=>'2025-01-10','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'Y2W','color_name1'=>'パーセクブルーNo.4','color_name2'=>'ブルー','body_number'=>'CA4AA-258832','doc_date'=>'2025-01-21','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'PSE','color_name1'=>'サンディベージュ','color_name2'=>'ベージュ','body_number'=>'CA4AA-258645','doc_date'=>'2025-01-22','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'W9K','color_name1'=>'ブラヴォドブラック','color_name2'=>'ブラック','body_number'=>'CA4AA-259068','doc_date'=>'2025-01-31','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'W9K','color_name1'=>'ブラヴォドブラック','color_name2'=>'ブラック','body_number'=>'CA4AA-260295','doc_date'=>'2025-02-28','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'9','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'PSE','color_name1'=>'サンディベージュ','color_name2'=>'ベージュ','body_number'=>'CA4AA-258832','doc_date'=>'2025-03-07','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツ','model'=>'UZ50M1','color_code'=>'PSE','color_name1'=>'サンディベージュ','color_name2'=>'ベージュ','body_number'=>'CA4AA-254642','doc_date'=>'2025-03-07','quantity'=>'1','unit'=>'UN','maker_price'=>'162000','gross_price'=>'131200','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツバスケット','model'=>'UZ0BM1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-253726','doc_date'=>'2024-08-26','quantity'=>'1','unit'=>'UN','maker_price'=>'181000','gross_price'=>'152000','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツバスケット','model'=>'UZ0BM1','color_code'=>'YWG','color_name1'=>'グラスミッドナイトブラウン','color_name2'=>'ブラウン','body_number'=>'CA4AA-255404','doc_date'=>'2024-10-14','quantity'=>'1','unit'=>'UN','maker_price'=>'181000','gross_price'=>'152000','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツバスケット','model'=>'UZ0BM1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-257682','doc_date'=>'2024-12-13','quantity'=>'1','unit'=>'UN','maker_price'=>'181000','gross_price'=>'152000','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツバスケット','model'=>'UZ0BM1','color_code'=>'YWG','color_name1'=>'グラスミッドナイトブラウン','color_name2'=>'ブラウン','body_number'=>'CA4AA-260687','doc_date'=>'2025-03-07','quantity'=>'1','unit'=>'UN','maker_price'=>'181000','gross_price'=>'152000','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
        Inventory::create(['material_code'=>'','material_name'=>'レッツバスケット','model'=>'UZ0BM1','color_code'=>'30H','color_name1'=>'ソリッドスペシャルホワイトNo.2','color_name2'=>'ホワイト','body_number'=>'CA4AA-260869','doc_date'=>'2025-03-12','quantity'=>'1','unit'=>'UN','maker_price'=>'181000','gross_price'=>'152000','type_dlv'=>'01','type_cali'=>'01','type_theft'=>'02','type_cr1_1'=>'05','type_cr1_2'=>'02','type_zr_ext'=>'02','type_zr_moto'=>'01','text_inv'=>'','remarks_inv'=>'','status_inv'=>'0','mat_doc_no'=>'','item_number'=>'','created_by'=>'admin','changed_by'=>'admin',]);
    }
}
